// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UUID_Generator
{
    internal sealed partial class Vsix
    {
        public const string Id = "UUID_Generator.3f59626d-3766-47a7-9194-6c4c22df3ffd";
        public const string Name = "UUID Generator";
        public const string Description = @"UUID Generator (GUID/ULID) as UUID v4";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "André Rodi";
        public const string Tags = "UUID, GUID, ULID";
    }
}
